version: '3.8'

services:
  db:
    image: postgres:15
    container_name: puma_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: dockerfile.django.worker
    container_name: puma_backend
    volumes:
      - .:/app:rw
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: "1"
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

volumes:
  postgres_data: