services:
  db:
    image: postgres:15
    container_name: puma_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - puma_network

  backend:
    build:
      context: .
      dockerfile: dockerfile.django
    container_name: puma_backend
    volumes:
      - .:/app:rw
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: "1"
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    networks:
      - puma_network

  redis:
    image: redis:7-alpine
    container_name: puma_redis
    ports:
      - "6379:6379"
    depends_on:
      - db
      - backend
    networks:
      - puma_network

  worker:
    container_name: puma_worker
    build:
      context: .
      dockerfile: dockerfile.django.worker
    volumes:
      - .:/app:rw
    depends_on:
      - db
      - redis
    environment:
      DEBUG: "1"
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379/0
    networks:
      - puma_network

volumes:
  postgres_data:

networks:
  puma_network:
