FROM debian:12.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y git curl socat && \
    curl -sSL https://get.microsandbox.dev | sh

COPY entrypoint.sandbox.sh /app/
RUN chmod +x /app/entrypoint.sandbox.sh

ENTRYPOINT ["sh", "/app/entrypoint.sandbox.sh"]
CMD ["/root/.local/bin/msb", "server", "start", "--dev", "--port", "5555"]