version: '3.8'

services:
  db:
    image: postgres:15
    container_name: puma_db
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: dockerfile.django.worker
    container_name: puma_backend
    volumes:
      - .:/app:rw
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: "1"
      DJANGO_SETTINGS_MODULE: django_prog.settings
      DATABASE_URL: postgres://your_user:your_password@db:5432/your_database

volumes:
  postgres_data: